export const ADMIN_CONTROL_ROOM_SECTIONS = [
  {
    key: 'command-center',
    title: 'Command Center',
    description: 'Executive live operations overview for CEO/CTO decisions.',
    subHeadings: [
      ['Live Overview', 'Overall platform status'],
      ['Revenue Snapshot', 'Revenue & collections'],
      ['Active Subscriptions', 'Total active customers'],
      ['AI Performance', 'AI handled vs human'],
      ['Communication Health', 'WhatsApp/call health'],
      ['Enterprise Alerts', 'Enterprise issues'],
      ['Critical Alerts', 'Urgent issues'],
      ['Live Activity Feed', 'Real-time updates'],
      ['AI Insights', 'AI-generated suggestions'],
    ],
  },
  {
    key: 'subscriptions',
    title: 'Subscriptions',
    description: 'Lifecycle, monetization, and control of all customer subscriptions.',
    subHeadings: [
      ['All Subscriptions', 'All customers'],
      ['Active Plans', 'Running subscriptions'],
      ['Trials', 'Trial users'],
      ['Expiring Soon', 'Upcoming renewals'],
      ['Paused Accounts', 'Temporarily paused'],
      ['Blocked Accounts', 'Suspended users'],
      ['Credits & Usage', 'AI credits & limits'],
      ['Module Access', 'Active modules'],
      ['Billing History', 'Payment records'],
      ['Subscription Actions', 'Upgrade/block/pause'],
    ],
  },
  {
    key: 'plans-pricing',
    title: 'Plans & Pricing',
    description: 'Commercial packaging, limits, offers, and pricing governance.',
    subHeadings: [
      ['All Plans', 'Available plans'],
      ['SalesPal Plans', 'Module pricing'],
      ['AssistPal Plans', 'Reminder AI pricing'],
      ['Enterprise Plans', 'Enterprise pricing'],
      ['Credits System', 'Usage credits'],
      ['Coupons & Offers', 'Discounts'],
      ['Plan Limits', 'Usage/features'],
      ['Add/Edit Plans', 'Plan management'],
    ],
  },
  {
    key: 'ai-control',
    title: 'AI Control',
    description: 'Provider strategy, quality controls, prompting, costs, and fallback logic.',
    subHeadings: [
      ['LLM Providers', 'Gemini/OpenAI/Claude'],
      ['Image AI Providers', 'Flux/OpenAI/etc'],
      ['Video AI Providers', 'Kling/Runway/etc'],
      ['Voice Providers', 'STT/TTS systems'],
      ['AI Rules', 'AI behavior settings'],
      ['Escalation Rules', 'Human takeover'],
      ['AI Memory', 'Memory controls'],
      ['Prompt Controls', 'Master prompts'],
      ['AI Usage Tracking', 'Token/API usage'],
      ['AI Cost Tracking', 'Cost to SalesPal'],
      ['Customer AI Pricing', 'Customer pricing setup'],
      ['Credit Consumption Rules', 'Credits per AI action'],
      ['Media Quality Controls', 'HD/4K generation rules'],
      ['Provider Switching', 'Change provider instantly'],
      ['AI Logs & Failures', 'AI issues/errors'],
      ['AI Fallback Systems', 'Backup AI providers'],
    ],
  },
  {
    key: 'communications',
    title: 'Communications',
    description: 'Cross-channel operational reliability and compliance.',
    subHeadings: [
      ['WhatsApp Control', 'WhatsApp management'],
      ['Calling System', 'Tata calling'],
      ['SMS & Email', 'Messaging providers'],
      ['Template Management', 'Meta templates'],
      ['Campaign Health', 'Delivery/reporting'],
      ['Opt-Out & DND', 'Compliance'],
      ['Failed Deliveries', 'Delivery issues'],
      ['Provider Status', 'API health'],
    ],
  },
  {
    key: 'modules',
    title: 'Modules',
    description: 'Global module governance, rollout policy, and maintenance operations.',
    subHeadings: [
      ['Marketing Module', 'Global controls'],
      ['Sales Module', 'Global controls'],
      ['Post-Sale Module', 'Global controls'],
      ['Support Module', 'Global controls'],
      ['AssistPal Module', 'Global controls'],
      ['Enterprise APIs', 'API access'],
      ['Feature Rollout', 'Beta/live features'],
      ['Maintenance Mode', 'Module downtime'],
    ],
  },
  {
    key: 'business-sources',
    title: 'Business Sources',
    description: 'Lead-source intelligence, partner contribution, and source-driven growth.',
    subHeadings: [
      ['Direct Business', 'Organic/company leads'],
      ['Social Media Leads', 'Facebook/Instagram'],
      ['Google & Website Leads', 'Organic search'],
      ['Business Development', 'Offline/team leads'],
      ['Ascend Alliance', 'Freelancer/agencies'],
      ['Referral Business', 'Influencer/user referrals'],
      ['Enterprise Inquiries', 'Enterprise leads'],
      ['Source Analytics', 'Revenue by source'],
      ['Partner Rankings', 'Top performers'],
    ],
  },
  {
    key: 'enterprise',
    title: 'Enterprise',
    description: 'Enterprise pipeline, custom requests, SLA, billing, and integration health.',
    subHeadings: [
      ['Enterprise Requests', 'Incoming requests'],
      ['Custom Requirements', 'Client needs'],
      ['White-label Requests', 'Branding/domain'],
      ['API Requests', 'Enterprise APIs'],
      ['SLA Monitoring', 'Service health'],
      ['Dedicated Support', 'Priority handling'],
      ['Enterprise Billing', 'Enterprise payments'],
      ['Integrations', 'Custom integrations'],
    ],
  },
  {
    key: 'admin-roles',
    title: 'Admin & Roles',
    description: 'Platform administration hierarchy, permissions, and security controls.',
    subHeadings: [
      ['Super Admins', 'Full platform control'],
      ['Admins', 'High-level management'],
      ['Sub Admins', 'Limited management'],
      ['Roles & Permissions', 'Access control'],
      ['Team Management', 'Internal teams'],
      ['Activity Logs', 'Who did what'],
      ['Access Restrictions', 'Security controls'],
      ['Session Management', 'Active logins'],
      ['2FA & Security', 'Login protection'],
    ],
  },
  {
    key: 'analytics',
    title: 'Analytics',
    description: 'Revenue, growth, AI, cost, and churn intelligence for strategic decisions.',
    subHeadings: [
      ['Revenue Analytics', 'Revenue growth'],
      ['Subscription Analytics', 'Customer growth'],
      ['AI Analytics', 'AI performance'],
      ['Communication Analytics', 'Call/WhatsApp stats'],
      ['Module Analytics', 'Module usage'],
      ['AI Cost Analytics', 'AI expenses'],
      ['AssistPal Analytics', 'Reminder performance'],
      ['Churn Analysis', 'Cancellation risks'],
      ['Growth Insights', 'AI suggestions'],
    ],
  },
  {
    key: 'alerts',
    title: 'Alerts',
    description: 'Unified alerting for technical, business, and security risks.',
    subHeadings: [
      ['Critical Alerts', 'Urgent issues'],
      ['AI Alerts', 'AI problems'],
      ['Communication Alerts', 'WhatsApp/call issues'],
      ['Billing Alerts', 'Payment failures'],
      ['Enterprise Alerts', 'SLA risks'],
      ['Abuse Detection', 'Spam/misuse'],
      ['Security Alerts', 'Login/security issues'],
      ['Alert History', 'Past alerts'],
    ],
  },
  {
    key: 'support-ops',
    title: 'Support Ops',
    description: 'Support command operations, SLA throughput, and resolution quality.',
    subHeadings: [
      ['Global Tickets', 'All support tickets'],
      ['Critical Complaints', 'High-priority issues'],
      ['AI Resolution Rate', 'AI solved support'],
      ['Human Escalations', 'Manual intervention'],
      ['SLA Performance', 'Resolution timing'],
      ['Feedback Ratings', 'Customer ratings'],
      ['Support Analytics', 'Team performance'],
    ],
  },
  {
    key: 'settings',
    title: 'Settings',
    description: 'Global platform settings, security, compliance, and integrations.',
    subHeadings: [
      ['Platform Settings', 'Global configs'],
      ['Branding & Themes', 'Platform branding'],
      ['Workflow Automation', 'Automation rules'],
      ['Notifications', 'Alert settings'],
      ['Security Settings', 'Security controls'],
      ['Compliance Rules', 'DND/privacy'],
      ['Audit Logs', 'Activity history'],
      ['Integrations', 'API/provider configs'],
    ],
  },
];

export const ADMIN_SECTION_MAP = ADMIN_CONTROL_ROOM_SECTIONS.reduce((acc, section) => {
  acc[section.key] = section;
  return acc;
}, {});

